### ISSUE TITLE
Add support for sets? (3, rossberg, ?)

### ISSUE THREAD

**Issue by 702fbtngus** [Wasm-DSL/spectec#104]

**Comment by rossberg** [comment]
I have generalised the composition operator `++` to plain sequences and added an element-of operator `<-` on sequences (which renders as ∈). With that, it's possible to use sequences, i.e. lists, as sets, using `++` for union.

We may want to customise notation to something a little bit more set-looking for the spec document, but that can be done with hints:
```
def $set(syntax X, X*) hint(show `{X*})
def $set(syntax X, X*) = X*

def $union(syntax X, X_1*, X_2*) hint(show %2 latex("\\cup") %3)
def $union(syntax X, X_1*, X_2*) = X_1* ++ X_2*
```
