### ISSUE TITLE
CI broken

### ISSUE THREAD

**Issue by rossberg** [Wasm-DSL/spectec#111]
Hey folks,

CI has been broken since [this commit](https://github.com/Wasm-DSL/spectec/commit/f8f23ad04a539ba63e285b74e6bb3d0a6cae90fe). The prose renderer incorrectly generates math with a macro invocation for `\zbytes` after this change. I don’t know where that’s coming from, something somehow bypasses the show hints in the Latex renderer. Could someone please investigate?

Please make sure that CI is always green. Either run `make ci` locally before pushing, or let github do it by creating a PR. And in case it's broken accidentally (can happen, I certainly have been guilty of that, usually when forgetting to promote test expectations), please fix it right away, even if that might require reverting the change.

**Comment by jaehyun1ee** [comment]
CI was broken after [this commit](https://github.com/Wasm-DSL/spectec/tree/3dc017c83c8cfb39c6beda9240c3ae3f9100de45), where it introduces an AST node `InvCallE` for inverse function application. The prose renderer did not handle the case properly, which broke the spec CI.

#109 handles the problem with `InvCallE` rendering, will merge on @rossberg's approval :)

**Comment by rossberg** [comment]
Cool, thanks for the fast fix!

Ah, I was inferring from the CI actions log, where the other commit was the first that showed that specific failure. Perhaps something else masked it on your commit.
