### ISSUE TITLE
Rendering of `null?`

### ISSUE THREAD

**Issue by f52985** [Wasm-DSL/spectec#125]
Hi,

This is just a simple question about the difference between the original and the spectec-written spec for the validation of `convert`.

The original spec has a premise that checks if two `null?`s are equal:
![스크린샷 2024-09-11 오후 5 57 27](https://github.com/user-attachments/assets/8e89dedf-20a0-456f-bb01-d57d2648ee68)

But the spectec-written spec does not have it:
![스크린샷 2024-09-11 오후 6 02 39](https://github.com/user-attachments/assets/6a7933af-e7b7-4da8-9581-8c1e49127429)

Is this an intended modification of the spec?

**Comment by rossberg** [comment]
This is saying the same thing. The SpecTec is using a meta-variable that is the same on both sides, so the equality is implicit.

**Comment by rossberg** [comment]
Ah, actually, that is a problem. With that rendering hack it does not make sense. I'll prepare a fix.
