### ISSUE TITLE
Parse error for nested brackets

### ISSUE THREAD

**Issue by 702fbtngus** [Wasm-DSL/spectec#49]
I'm trying to write Wasm-DSL for vector instructions in branch 'al-vector,' and I guess that current SpecTec doesn't support parsing nested brackets. Below is my try:
```
rule Step_pure/i8x16.swizzle:
  (VVCONST V128 cv_1) (VVCONST V128 cv_2) (I8X16.SWIZZLE) ~> (VVCONST V128 c')
  -- if i* = $lanes(SHAPE I8 16, cv_2)
  -- if c* = $concat($lanes(SHAPE I8 16, cv_1), $exp(0, 240))
  -- if $lanes(SHAPE I8 16, c') = c*[i*[k]]^(k<16)
                                       ^
```
Here, the last line is line number 192. Running `dune test test-prose` results as below bug:

`+6-reduction.watsup:192.40-192.41: unexpected token`

I think the SpecTec engine needs to support nested brackets, since it is also used in the below spec.
![image](https://github.com/Wasm-DSL/spectec/assets/79245586/cff47e1b-f566-438d-9270-9de1e087b09e)

**Comment by rossberg** [comment]
Hm, right. I think the problem here isn't the indexing, but the `*` -- in this position, it is parsed as multiplication. I'll think about a way to address this.

**Comment by rossberg** [comment]
Okay, this should be possible to express now if you either escape the `i*` as `$(i*)[0]` or put it in regular parens `(i*)[0]`. The former will not appear in the rendered Latex, so probably is what you want here.

**Comment by 702fbtngus** [comment]
Now using either `$(i*)[0]` or `(i*)[0]` works. Thank you :)
