### ISSUE TITLE
Parameterized relations

### ISSUE THREAD

**Issue by tlively** [Wasm-DSL/spectec#56]
Hello!

Over in the [shared-everything-threads proposal](https://github.com/webassembly/shared-everything-threads/) we envision parameterizing the `Instr_ok` relation (and a number of other relations) with a `share` where `share` is either `shared` or `eps`. Does the DSL support parameterizing relations? If not, is there another way to express something similar?

**Comment by rossberg** [comment]
In theory, we could make relations parameterised, but that's not how you normally express this. Instead, the thing simply is another component of the relation or its classifier, e.g.:
```
syntax sharing = SHARED?
relation Thing_ok: |- thing : OK(sharing)
```
With 3.0 we already have a couple of relations like that.

In the case of instructions, if we need to distinguish them by "sharedness" (not sure how this would come up?), it would presumably become part of the instruction type:
```
syntax instrtype = sharing resulttype ->localidx* resulttype
```

**Comment by tlively** [comment]
Excellent, that's exactly what I need. Thank you!

(FWIW, we need to distinguish instructions by sharedness to ensure that shared function activation frames do not contain unshared values even as temporary values. This is for future-compatibility with shared continuations.)
