### ISSUE TITLE
[backend-prose] Separate text and math rendering (and use Latex backend for the latter)

### ISSUE THREAD

**Issue by rossberg** [Wasm-DSL/spectec#59]
The prose renderer appears to be rendering some running text using `\textrm` (inside math?). That violates various Latex principles and defeats things like font consistency and aspects of layout, especially when done inside Sphinx.

That is, text and math ought to be separated: math can appear in text, but not the other way round.

Moreover, the prose backend should render everything that is wrapped into `:math:` using the Latex backend, to ensure notational consistency and single modification points for changing notation rendering. No other module should depend on internals like exposing the expand_exp function.

**Comment by jaehyun1ee** [comment]
**`\textrm`s to render text inside math**

Yes, it was a hack to get things done quickly, and definitely should be addressed.
I'll try to address this issue it soon :)

**Using the Latex backend**

This is rather complicated. The Latex backend takes EL as input, but the parts that are enclosed in `:math:` are all AL expressions. I do agree that inlined math blocks should be rendered using the Latex backend, for we should pursue a coherent style of math representations. Hence, we have to somehow turn our AL AST into EL AST beforehand. 

The problem I had when implementing the AL renderer was that, there was no explicit link between EL and AL expressions. When EL is elaborated to IL, IL AST has EL's source location annotated by `note-phrase`, but not the EL AST that it originated from. Correspondingly, AL AST does not have an explicit backlink to its counterparts in EL AST. So it seemed like the only practical option was to render AL expressions separately in `backend-prose/render.ml`.

And some explanation on exposing the `expand_exp` function: The single dependency that `backend_prose` has upon `backend_latex` is for rendering expressions with display hints. It is done by:
- Collect the display hints, which are essentially EL expressions, from the EL script;
- When rendering `CaseE` or `CallE`, lookup for the hint expression;
- By `expand_exp` function, fill in the `HoleE`s of the hint expression with temporary placeholders;
- Render it using the Latex backend;
- Replace the placeholders with the rendered AL subexpressions of `CaseE` or `CallE`;

So in effect, this establishes a link between some AL expressions and EL hint expressions.

So I can think of two solutions now.

**(1) Implement an AL expression-to-EL expression translation phase.**

At the moment I am not sure if this should be trivial, but if it is possible to do so, then it would solve our problem.

**(2) Carry the EL AST along while translating EL-to-IL-to-AL.**

Or we may augment the `note`s in IL to hold EL AST also. This must be tedious to implement.

I suppose (1) is a better solution, but if (1) doesn't seem to work quite as expected, we may have to turn to option (2).
I'll try implementing the (1) option and share the status.

**Comment by rossberg** [comment]
Thanks @jaehyun1ee!

Yes, (1) would be the preferred solution (and also works for cases not coming from the EL directly). Since the math appearing in prose uses a subset of the formal notation, I would expect this mapping to be pretty straightforward. But let me know if there are cases that are difficult to handle, perhaps we can just extend the EL expression AST to include them or find some other trick.

**Comment by jaehyun1ee** [comment]
@rossberg, please take a look at #61 :)
