### ISSUE TITLE
[spec-2.0/3.0] Add missing SIMD instructions

### ISSUE THREAD

**Issue by rossberg** [Wasm-DSL/spectec#70]
Several SIMD instructions are currently missing from the specs:
- [x] iNxM.mul
- [ ] i8x16.popcnt
- [ ] txN.avgr_u
- [ ] i16x8.q15mulr_sat_s

**Comment by 702fbtngus** [comment]
In the spec, popcnt is included in viunop, and mul, avgr_u, and q15mulr_sat_s are included in vibinop.

**Comment by rossberg** [comment]
Indeed they are! Hm, that's odd, they're somehow missing on my parameters branch. Perhaps they moved around at some point, and I missed that while resolving a merge conflict.

Anyway, I apologise for the noise! I'll reintroduce them on the branch and close this issue.

**Comment by rossberg** [comment]
Done. I added the relevant syntactic side conditions, which where the reason for separating them from binops in the paper spec in the first place. Also merged in minmax ops and satbinops.
