### ISSUE TITLE
[backend-prose] Roundtrip atoms

### ISSUE THREAD

**Issue by rossberg** [Wasm-DSL/spectec#74]
The IL-2-AL conversion turns most atoms into plain strings, but does not reconstruct them when rendering. This means that various user-defined notation will not be rendered correctly when generated through the prose backend.

Ideally, the AL should represent atoms in a non-lossy fashion, such that they can be converted back to EL for rendering.

**Comment by jaehyun1ee** [comment]
I believe the current IL-2-AL conversion of atoms is not lossy.
Reading `il2al/translate.ml`, only three variants of IL atom are translated to AL, without losing information.

(1) `Atom of string`

All `Il.Atom` is translated to `type kwd = (kwd', string) and kwd' = string` in AL.
Here, the `kwd'` corresponds to the field of `Il.Atom` and the second `string` corresponds to the note of `Il.atom` type.

(2) `Arrow`

All `Il.Arrow` is translated to `Al.Arrow`, which is of type `Al.infixop`.
Yet, the AL-to-EL-expr translation assumes that the type of `Il.Arrow` (which is in its note) is always an empty string.

(3) `ArrowSub`

Similar to (2), All `Il.ArrowSub` is translated to `Al.ArrowSub`, of type `Al.infixop`.

**Comment by rossberg** [comment]
Well, that is assuming that is all the notation that's ever used. But of course, we want users to be able to use all notation supported by the frontend without having to change the rendering backend(s).

**Comment by jaehyun1ee** [comment]
@rossberg I believe atoms can roundtrip now :) Can we close this issue?

**Comment by rossberg** [comment]
Yes. :)
