### ISSUE TITLE
Replacement for CONVERT_SAT

### ISSUE THREAD

**Issue by HoseongLee** [Wasm-DSL/spectec#76]
In the pull request #72 commit 1fd8f78 CONVERT_SAT was removed from the syntax of cvtop

```diff
- syntax cvtop = | CONVERT | REINTERPRET | CONVERT_SAT
+ syntax cvtop = | CONVERT | REINTERPRET
```

However, it seems that with this change, we cannot express trunc_sat as it collides with trunc
So, I believe we need a replacement or a workaround for this problem

**Comment by rossberg** [comment]
Oops, that was unintentional, I probably messed up resolving some merge conflicts. (Surprising that this didn't cause any issues...)

Please feel free to add it back.
